### PR TITLE
Add support for LPC4322

### PR DESCRIPTION
**Pull request by mmahadevan108**
Signed-off-by: Mahadevan Mahesh <Mahesh.Mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@0xc0170

**Comment by mmahadevan108** [comment]
Are there any comments/suggestions on this pull request

**Comment by mmahadevan108** [comment]
@maclobdell

**Comment by mmahadevan108** [comment]
@c1728p9 . This is update to the project generator to generate projects for LPC4322. I am working to add support for this interface chip under DAPLink.

**Comment by c1728p9** [comment]
Seems good to me. @0xc0170 can you review and merge if this looks good?

**Comment by 0xc0170** [comment]
Sorry for the delay

**Pull request merged**
