### PR TITLE
Fix cortex uvision5

### PR DESCRIPTION
**Pull request by 0xc0170**
Adding uvision5 support for cortex-m MCUs

+ adding M23 support as it might be requested soon, better to have it in now

cc @mmahadevan108

### CODE REVIEW

**Comment by 0xc0170** [comment]
```
FlashAlgo (master -> origin)
progen generate -t uvision5
```

Does not error with this PR

**Comment by 0xc0170** [comment]
v0.2.38 published. @mmahadevan108 Please test locally

**Comment by mmahadevan108** [comment]
Thank you. 0.2.38 works fine. I am able to generate CM33 projects. Looks like FlashAlgo uvision project template files need to be updated for ARMC6. I have added an issue for this in the FlashAlgo repo, https://github.com/mbedmicro/FlashAlgo/issues/51

**Comment by 0xc0170** [comment]
Great ! happy to help

**Pull request merged**
