### PR TITLE
uvision: add cortex-m33 definition

### PR DESCRIPTION
**Pull request by 0xc0170**
@mmahadevan108 Please review

Shall I add fpu version or any other now? Not sure if your request was just for generic cortex-m33 definiton or there is a bug somewhere else ?

### CODE REVIEW

**Comment by 0xc0170** [comment]
Should fix #126

I found cortex-m33 only in cmsis packs. This means that a project should be uvision5 , and have a valid pack installed. The rest uvision will add to the project itself.

**Comment by mmahadevan108** [comment]
@0xc0170 Thank you. progen command succeeded without any errors. However I am seeing the below  message pop-up when importing the project into Keil.
_______________________________________
Error: Device not found 

Device: ARMCM33
Vendor: ARM
______________________________________

Is there a pack I need to install in Keil, I am using version 5.26 and have the appropriate license.
Please update your device selection

**Comment by 0xc0170** [comment]
how do you generate your project? If you can provide me a way to reproduce the error, I will and fix it

**Comment by mmahadevan108** [comment]
I think the issue is in my Keil setup. For some reason I do not see Cortex-M7, Cortex-M23, Cortex-M33 in the Device list under ARM.

Does it have to do anything with the way the project is generated.

**Comment by 0xc0170** [comment]
When I was checking support for these new cores, there is cmsis pack - I recall called like ARM cmsis pack or similar to provide only ARM cores. 
Go to the pack manager and search cortex m33, there should be cmsis pack for it. I am not currently on the machine but can check tomorrow what pack I have locally.

**Comment by 0xc0170** [comment]
I can confirm this yaml file works with uvision5 (5.26), here's a picture

image

I am using lpc1768 target to quickly test (redefines MCU to cortex-m33 for testing purposes). The core is found without any issue. You can find in the picture the version of cmsis pack I installed

**Comment by 0xc0170** [comment]
One thing I have missed, will fix - here's uvision but should be actually uvision5 (as previously we suppored 4)

**Comment by 0xc0170** [comment]
Fixed, this should be ready for intergration. @mmahadevan108 if you have a target that uses this, please send PR adding the new target based on this. I'll merge this but will wait with publishing until you approve that it works for you

**Comment by mmahadevan108** [comment]
I am seeing the below:

(venv) PS C:\mbedmicro\FlashAlgo> progen generate -t uvision5
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\progen.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\project_generator\main.py", line 62, in main
    return args.func(args)
  File "c:\python27\lib\site-packages\project_generator\commands\generate.py", line 30, in run
    if project.generate(args.tool, copied=args.copy, copy=args.copy) == -1:
  File "c:\python27\lib\site-packages\project_generator\project.py", line 552, in generate
    files = exporter(self.project['export'], self.settings).export_project()
  File "c:\python27\lib\site-packages\project_generator\tools\uvision.py", line 552, in export_project
    path, files = self._export_single_project('uvision5')
  File "c:\python27\lib\site-packages\project_generator\tools\uvision.py", line 452, in _export_single_project
    self._set_target(expanded_dic, uvproj_dic, tool_name)
  File "c:\python27\lib\site-packages\project_generator\tools\uvision.py", line 318, in _set_target
    raise RuntimeError("Target %s is not supported. Please add them to https://github.com/project-generator/project_gene
rator_definitions" % expanded_dic['target'].lower())
RuntimeError: Target cortex-m4 is not supported. Please add them to https://github.com/project-generator/project_generat
or_definitions

**Comment by 0xc0170** [comment]
> RuntimeError: Target cortex-m4 is not supported. Please add them to https://github.com/project-generator/project_generat

What is your target? I don't think there's target "cortex-m4" , rather this is MCU only. Can you share with me your yaml file, and what are you trying to build? Using FlashAlgo master?

**Comment by mmahadevan108** [comment]
I am building FlashAlgo master

**Comment by 0xc0170** [comment]
Thanks, will do later today , to reproduce this locally. It should find the MCU and use it, there have not been any change for some time

**Comment by 0xc0170** [comment]
We are missing cortex definitions for uvision5 (I'll fix that in separate PR). Thus use uvision for now (project should be compatible)

**Pull request merged**
