### PR TITLE
Idea for definitions format

### PR DESCRIPTION
**Pull request by matthewelse**
Here's my idea for the structure of target definitions - we can use this pull request for discussion about the format.

### CODE REVIEW

**Comment by 0xc0170** [comment]
Some cosmetic but better be said now then never :)
- using lower case for names in the files and filenames?
- unified format - using the same format for yaml as in the project generator? :

```
mcu:
    - name
```

So it becomes valid if there are two or more.
- where is mcu definition for each tool ? This for example for uvision:

```
        'nRF51822AA': {
            'TargetOption': {
                'Device': 'nRF51822_xxAA',
                'Vendor': 'Nordic Semiconductor',
                'Cpu': 'IROM(0x00000000,0x40000) IRAM(0x20000000,0x4000) CPUTYPE("Cortex-M0") CLOCK(16000000) ELITTLE',
                'FlashDriverDll': 'UL2CM3(-S0 -C0 -P0 -FD20000000 -FC1000 -FN1 -FF0nrf51xxx -FS00 -FL0200000 -FP0($$Device:nRF51822_xxAA$Flash\nrf51xxx.flm))',
                'DeviceId': 0,
                'SFDFile': '$$Device:nRF51822_xxAA$SVD\nrf51.xml'
            }
        },
```
- should mcu have folders of manufacturers for easier navigation? If yes, we need some details in board definitions to know where to find the mcu. Might be like mcu: nxp/lpc1768 or vendor: and mcu:
- use dash or underscore for names : mbed-lpc1768 vs mbed_lpc1768 ?
- should we have a list of supported boards in the root directory , or mcus ? To be able to return as a list of supported boards and as well easier to get the file ?

**Comment by matthewelse** [comment]
I've just added a few extra things - the additions in this pull request are my idea of what it should be, based on discussions I had with @0xc0170, though there's obviously room for improvement before we decide on a final structure.

**Comment by aethaniel** [comment]
@matthewelse, seems perfect to me.
I only hope this generator is not only dedicated to mbed ;-)

**Comment by 0xc0170** [comment]
@aethaniel No it's not. It's generic tool.
I noticed in the above example some mbed macros, will respond later to that

**Comment by matthewelse** [comment]
@aethaniel By mbed macros do you mean `TARGET_LPC1768` and similar?

**Comment by 0xc0170** [comment]
Yes, can you remove all that mbed macros there or is to show specific settings for boards? :) I'll pull your branch and add some more magic

**Comment by matthewelse** [comment]
@0xc0170 @aethaniel any thoughts about where this repository should be cloned to?

**Comment by matthewelse** [comment]
@0xc0170 I was thinking that the macros could either be added automagically by project_generator, for example if the core is called Cortex M3 then it would add the macro `CORE_CORTEX_M3` or if it's on the board `FRDM-K64F` then it would add `BOARD_K64F` and then there could be a command line or project setting for mbed style macros e.g. `TARGET_CORTEX_M3` etc

**Comment by 0xc0170** [comment]
the load command will accept a path so this repo can be anywhere. 

What I am considering is to rename a board to a target. As I can have frdm-k64f and project-frdm-k64f targets (one board, multiple targets). One is default, nothing specific. The other one can have specific settings to a project.

Now back to your records

```
#target yaml - target/mbed-board-lpc1768
target:
    name:
        - mbed-board-lpc1768
    mcu:
        - mcu/nxp/lpc1768

# another target based on above mcu - target/board-lpc1768
target:
    name:
        - board-lpc1768
    mcu:
        - mcu/nxp/lpc1768

# target can be just arm core (uvision or IAr supports this for instance)
target:
    name:
        - cortex-m0
    mcu:
        - mcu/arm/cortex-m0

#mcu yaml file - mcu/nxp/lpc1768.yaml
mcu:
    vendor:
        - nxp
    name:
        - lpc1768
    core:
        - cortex-m4
tools:
    uvision:
        - # here the mcu info
    iar:
        - # here the muc info
```

**Comment by matthewelse** [comment]
:+1:

**Comment by 0xc0170** [comment]
I sent #2, which looks like I proposed above.

**Comment by 0xc0170** [comment]
@matthewelse I close this, merge the second one as a starting point.

**Pull request closed without merging**
