### PR TITLE
add support for NXP MK22FN128VLH10

### PR DESCRIPTION
**Pull request by dotnfc**

### CODE REVIEW

**Comment by 0xc0170** [comment]
Can you please remove the merge commit (the first one) ?

**Comment by 0xc0170** [comment]
There are failures in the last commit

```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/home/travis/build/project-generator/project_generator_definitions/project_generator_definitions/mcu/ambiq/ama3b1kk-kbr.yaml", line 46, column 25
```

See travis. I believe it should be `\t` there instead.

**Comment by 0xc0170** [comment]
yaml spec limitation. I remember hitting the same error. If you remove the tab from there and do instead `\t` it should work.

**Comment by 0xc0170** [comment]
Ive found the fix, just use space instead of space: https://github.com/project-generator/project_generator_definitions/commit/e26da4fcb690fd7595c5aad28c869bab1a45ce45#diff-e283044898a54c3ca716197441b39392002fe4ad829a38b1839337a50de7dd80L26 (similar issue was there).

did you use progen parser to get these yaml? I wonder if we should fix it within progen so tab is not there

**Comment by dotnfc** [comment]
try to fix error

**Pull request closed without merging**
