### PR TITLE
Add Cortex-M0+ MCU support

### PR DESCRIPTION
**Pull request by toyowata**
- Add cortex-m0p.yaml file

### CODE REVIEW

**Comment by 0xc0170** [comment]
What should be the name, cortex-m0+ or cortex-m0p or cortex-m0plus ?

**Comment by toyowata** [comment]
It should not be cortex-m0+ to avoid path name problem in most of host OS.

**Comment by 0xc0170** [comment]
> It should not be cortex-m0+ to avoid path name problem in most of host OS.

True that. Shall we go rather with m0plus? than m0p ? That's what you put for instance for gcc as cpu type, but in keil it's m0p.

**Comment by toyowata** [comment]
> Shall we go rather with m0plus? than m0p ?

Agreed. I changed the naming for the Cortex-M0+ and committed the yaml file. Please can you review.

**Comment by 0xc0170** [comment]
v0.2.5 released with this addition, thanks

**Pull request merged**
