### PR TITLE
[NUCLEO_L031K6] Add target

### PR DESCRIPTION
**Pull request by svastm**

### CODE REVIEW

**Comment by 0xc0170** [comment]
Is this for uvision4?

**Comment by svastm** [comment]
I used the command on a uvision5 project.

**Comment by 0xc0170** [comment]
It should be `uvision5` then please. This is not valid uvision4. If this will be used with uvision4, it would fail. For device packs, we should use uvision5.

**Comment by svastm** [comment]
In fact, this device is not supported by uvision4. I chose to generate a uv4 project because mbed does not support uv5 yet. Is there a better way to include the target ?

**Comment by 0xc0170** [comment]
I'll merge uvision5 to mbed this week. Then this device will get supported for the next release.
Please use uvision5 when generating yaml file. I'll merge then right away.  

  On Fri, Apr 22, 2016 at 10:37 AM, svastmnotifications@github.com wrote:  
In fact, this device is not supported by uvision4. I chose to generate a uv4 project because mbed does not support uv5 yet. Is there a better way to include the target ?

**Comment by svastm** [comment]
Perfect then. I have made the changes but not test if the project is well generated.

**Comment by 0xc0170** [comment]
Thanks, looking good. I'll create an issue, if progendef finds uvision used on uvision5, it should print an error and not produce yaml file.

**Comment by 0xc0170** [comment]
#55 is actually already there. I'll create a PR to fix that.

**Comment by 0xc0170** [comment]
v0.2.13 released. uvision5 is now on mbed master, please test it

**Comment by svastm** [comment]
Done and nothing looks broken. I don't have any extra features but, at least, I can avoid renaming the .uvproj in .uvprojx.

**Pull request merged**
